// Embeds brand WOFF fonts as base64 into src/lib/og-fonts.ts so satori can
// render OG images at runtime without depending on filesystem paths after the
// SSR bundle is built.
//
// Usage: node scripts/embed-fonts.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const fontsDir = path.join(root, 'src/assets/fonts');
const outFile = path.join(root, 'src/lib/og-fonts.ts');

const files = {
  syne800: 'syne-800.woff',
  pjs400: 'pjs-400.woff',
  pjs600: 'pjs-600.woff',
};

let out =
  '// AUTO-GENERATED by scripts/embed-fonts.mjs. Brand fonts (WOFF1) base64-embedded for satori OG rendering.\n' +
  '// Run: node scripts/embed-fonts.mjs after replacing files in src/assets/fonts.\n\n';

for (const [name, file] of Object.entries(files)) {
  const b64 = fs.readFileSync(path.join(fontsDir, file)).toString('base64');
  out += `export const ${name} = "${b64}";\n`;
}

out += '\nexport function fontBuffer(b64: string): Buffer {\n  return Buffer.from(b64, "base64");\n}\n';

fs.writeFileSync(outFile, out);
console.log(`Wrote ${outFile} (${out.length} bytes)`);
