services:
  fredy:
    image: ghcr.io/orangecoding/fredy:master
    container_name: renting-berlin-fredy
    ports:
      - "${FREDY_PORT:-9998}:9998"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./conf:/conf
      - ./db:/db
    restart: unless-stopped
    networks:
      - default
      - proxies

networks:
  proxies:
    external: true
    name: ${FREDY_PROXY_NETWORK:-proxies_default}
